name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2

      - uses: pdm-project/setup-pdm@main
        name: Setup PDM
        with:
          python-version: ${{ matrix.python-version }}
          enable-pep582: true

      - name: Install Dependencies
        run: pdm install

      - name: Run Tests
        run: pdm run tests --cov-report=html --cov-report=term

      - uses: actions/upload-artifact@v3
        with:
          name: coverage report
          path: htmlcov


  checks:
    name: Acceptance Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pre-commit/action@v2.0.3


  # docs:
  #   name: Build Documentation
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python-version: ["3.9"]

  #   steps:
  #     - uses: actions/checkout@v2

  #     - uses: pdm-project/setup-pdm@main
  #       name: Setup PDM
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #         enable-pep582: true

  #     - name: Install Dependencies
  #       run: pdm install

  #     - name: Build Docs
  #       run: pdm run docs-build

  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: docs
  #         path: docs/_build/html

  #     - name: Create docs commit
  #       run: |
  #         cd docs/_build/html
  #         touch .nojekyll
  #         git init
  #         git add -A
  #         git config --local user.email "action@github.com"
  #         git config --local user.name "Github Actions"
  #         git commit -m "deploy"
  #     - name: Force push to destination branch
  #       uses: ad-m/github-push-action@v0.5.0
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         branch: gh-pages
  #         force: true
  #         directory: ./docs/_build/html
